version: '0.1'

services:
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scraper
    network_mode: "host"
    restart: always
    ports:
      - '8445:8445'
  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile
    container_name: processor
    restart: always
    ports:
      - '8443:8443'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/var/lib/grafana/ssl/grafana.crt
      - GF_SERVER_CERT_KEY=/var/lib/grafana/ssl/grafana.key
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/certs/:/var/lib/grafana/ssl/
  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always

volumes:
  grafana-storage:
  prometheus_data: