global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: Api
    metrics_path: /scrape/prometheus
    scheme: https
    static_configs:
      - targets:
          - processor:8443
    tls_config:
      insecure_skip_verify: true  # This is the key